version: '3.9'

services:
  kiosk-voice-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    environment:
      - ENV=dev
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    
  kiosk-voice-main:
    build:
      context: .
      dockerfile: Dockerfile.main
    environment:
      - ENV=dev
    volumes:
      - .:/app
    ports:
      - "3003:3003"
