FROM python:3.9-slim

WORKDIR /app

# Copy application files
COPY . /app

# RUN apt-get update && apt-get install -y \
#     build-essential \
#     python3-dev \
#     gcc \
#     libffi-dev \
#     --no-install-recommends && \
#     rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set the entrypoint
CMD ["python3", "agent.py", "dev"]
